### PR TITLE
restructure, add cloud build

### PR DESCRIPTION
**Pull request by kanekv**

### CODE REVIEW

**Comment by kanekv** [comment]
[Restructure project](https://trello.com/c/sidvJ7oo/30-restructure-project)

**Comment by Herrera93** [comment]
Everything looks properly structured.
Something we should keep in mind is that if the exercises get more complex we may
need to organize the days libraries in folders instead of putting everything into a single file.
But I don't know we should organize it now or once it happens if it does. What do you think ?

**Comment by lifehug** [comment]
I like the cloud build addition, it'll be nice to see those pass. 

@Herrera93 looking at the code the days seem to be split into separate files and not a single file. I agree having everything in a single file would be difficult. 

Agree on the switching the test file name to day-3
screen shot 2018-11-20 at 9 12 42 am
screen shot 2018-11-20 at 9 12 53 am

**Comment by kanekv** [comment]
@Herrera93 renamed file please take a look again. Let's add folders when we see need for them (later).

**Pull request merged**
